### ISSUE TITLE
Can't parse the *.properties file

### ISSUE THREAD

**Issue by gecock** [RestComm/load-balancer-docker#20]
I'm seeing the following error and I'm unable to alter the configuration of the balancer to anything other than the default settings.

```
[Fatal Error] lb-configuration.properties:1:1: Content is not allowed in prolog.
2017-01-16 19:55:59,340 ERROR main - Could not load configuration from /opt/loadbalancer/config/lb-configuration.properties. Using default values. Message : Error parsing file:/opt/loadbalancer/config/lb-configuration.properties
```

I took a look at the Dockerfile and noticed that the *.properties file is being used for `${LOADER_BALANCER_CONFIG}`, which eventually gets propagated down to start_loadbalancer.sh to be used as the input for `-mobicents-balancer-config` in the java -jar command.  According to the documentation shouldn't that value be the *.xml config file? 

I was able to reproduce this error using the non-docker, jar install by specifying the *.properties file as my `-mobicents-balancer-config` variable.  Specifying the *.xml config file worked fine.

**Comment by leftyb** [comment]
@gecock Thank you for reporting.

We have fixed the issue. Please pull the latest container:
`restcomm/load-balancer:latest`

ps. after testing and confirm that everything works normally please close the issue.
Regards

**Comment by gecock** [comment]
It's definitely reading the .xml file now, but the LB won't bind to the address/port I specify. If I use the exact same file with the non-docker install the LB comes up successfully. Being that this issue was simply for reading the .xml file, I'll close this and open a separate issue for the current problems.
