### ISSUE TITLE
Add logs configuration similar to restcomm-docker.

### ISSUE THREAD

**Issue by leftyb** [RestComm/load-balancer-docker#7]
we need to be able to collect logs from there
similarly to how we do it at restcomm 
logs + wiresharks.

Change log level, etc.

**Comment by hamsterksu** [comment]
to collect logs you just need to execute `docker logs` 
in most cases loadbalancer will work with host network, so you can use `tcpdump` from host

**Comment by leftyb** [comment]
well we need to be able to keep logs for some time (e.g. weekly logs) in order to be able to troubleshoot if necessary. So the idea is to keep dally or less log rotated files.  
I agree using Docker log driver  can be one option to achieve that, but we need to include that at the container automatically when running docker.  
Same with wiresharks, we would like to store rotated wiresharks to able to troubleshoot in any case of failure.
